In [1]:
import pandas as pd
import numpy as np
import json

Read a JSON file that is generated by user_table.py

In [3]:
df = pd.read_json('output.json')

In [4]:
df

,Timestamp,Upload your photo!,Which question is this photo for?,Person 1 ID,Person 2 ID,Person 3 ID,Person 4 ID,Person 5 ID,Approved
0,2026-06-27 08:22:03.435000+00:00,https://drive.google.com/open?id=1XAu9xyGAPcdy...,8,6,8,8,20,,1

In [5]:
df.columns

Index(['Timestamp', 'Upload your photo!', 'Which question is this photo for?',
       'Person 1 ID', 'Person 2 ID', 'Person 3 ID', 'Person 4 ID',
       'Person 5 ID', 'Approved'],
      dtype='str')

In [6]:
df = df.rename(columns={'Upload your photo!': 'Link', 'Which question is this photo for?': 'Question'})
df.drop(columns=['Approved'], inplace=True)
# collapsed_df = pd.melt(df, id_vars=["Timestamp", "Link", "Question"], value_vars=[f" Person {i} ID" for i in range(1,6)], value_name="ID",).drop(columns=['variable'])

In [7]:
df

,Timestamp,Link,Question,Person 1 ID,Person 2 ID,Person 3 ID,Person 4 ID,Person 5 ID
0,2026-06-27 08:22:03.435000+00:00,https://drive.google.com/open?id=1XAu9xyGAPcdy...,8,6,8,8,20,

In [8]:
collapsed_df = pd.melt(
    df,
    id_vars=["Timestamp", "Link", "Question"],
    value_vars=[f"Person {i} ID" for i in range(1,6)],
    value_name="ID",)
collapsed_df["ID"] = (
    collapsed_df["ID"]
    .astype(str)
    .str.strip()
    .replace(["", "None", "NaN", "nan"], np.nan)
)
collapsed_df = collapsed_df.dropna(subset=["ID"])
collapsed_df = collapsed_df[['ID', 'Link', 'Question', 'Timestamp']]
collapsed_df

,ID,Link,Question,Timestamp
0,6,https://drive.google.com/open?id=1XAu9xyGAPcdy...,8,2026-06-27 08:22:03.435000+00:00
1,8,https://drive.google.com/open?id=1XAu9xyGAPcdy...,8,2026-06-27 08:22:03.435000+00:00
2,8,https://drive.google.com/open?id=1XAu9xyGAPcdy...,8,2026-06-27 08:22:03.435000+00:00
3,20,https://drive.google.com/open?id=1XAu9xyGAPcdy...,8,2026-06-27 08:22:03.435000+00:00

In [10]:
user_table_new = collapsed_df.to_dict(orient='records')
user_table_new

[{'ID': '6',
  'Link': 'https://drive.google.com/open?id=1XAu9xyGAPcdyUVpuciAoGLkQPu3KqcXA',
  'Question': 8,
  'Timestamp': Timestamp('2026-06-27 08:22:03.435000+0000', tz='UTC')},
 {'ID': '8',
  'Link': 'https://drive.google.com/open?id=1XAu9xyGAPcdyUVpuciAoGLkQPu3KqcXA',
  'Question': 8,
  'Timestamp': Timestamp('2026-06-27 08:22:03.435000+0000', tz='UTC')},
 {'ID': '8',
  'Link': 'https://drive.google.com/open?id=1XAu9xyGAPcdyUVpuciAoGLkQPu3KqcXA',
  'Question': 8,
  'Timestamp': Timestamp('2026-06-27 08:22:03.435000+0000', tz='UTC')},
 {'ID': '20',
  'Link': 'https://drive.google.com/open?id=1XAu9xyGAPcdyUVpuciAoGLkQPu3KqcXA',
  'Question': 8,
  'Timestamp': Timestamp('2026-06-27 08:22:03.435000+0000', tz='UTC')}]

In [21]:
user_df = pd.read_json('user_table.json')
# user_df[user_df['ID'] == 8]
user_df['ID'].value_counts()

ID
8     2
6     1
20    1
1     1
2     1
Name: count, dtype: int64

Create a DF from the JSON FILE to inspect the results here

In [11]:
with open('user_table.json', 'r') as file:
    user_table_list = json.load(file)
user_table_list

[{'ID': '6',
  'Link': 'https://drive.google.com/open?id=1XAu9xyGAPcdyUVpuciAoGLkQPu3KqcXA',
  'Question': 8,
  'Timestamp': '2026-06-27T08:22:03.435Z'},
 {'ID': '8',
  'Link': 'https://drive.google.com/open?id=1XAu9xyGAPcdyUVpuciAoGLkQPu3KqcXA',
  'Question': 8,
  'Timestamp': '2026-06-27T08:22:03.435Z'},
 {'ID': '8',
  'Link': 'https://drive.google.com/open?id=1XAu9xyGAPcdyUVpuciAoGLkQPu3KqcXA',
  'Question': 8,
  'Timestamp': '2026-06-27T08:22:03.435Z'},
 {'ID': '20',
  'Link': 'https://drive.google.com/open?id=1XAu9xyGAPcdyUVpuciAoGLkQPu3KqcXA',
  'Question': 8,
  'Timestamp': '2026-06-27T08:22:03.435Z'},
 {'ID': '1',
  'Link': 'https://drive.google.com/open?id=1eanFZGddjG0Krrj2tuPbxTnM5JrILFQm',
  'Question': 1,
  'Timestamp': '2026-06-25T15:39:15.084Z'},
 {'ID': '2',
  'Link': 'https://drive.google.com/open?id=1eanFZGddjG0Krrj2tuPbxTnM5JrILFQm',
  'Question': 1,
  'Timestamp': '2026-06-25T15:39:15.084Z'}]